title: Tobias Nash for PNCC
description: Tobias Nash PNCC 2025 - KAHA TAHI - Strong Together
url: https://github.com/humanathema/TobiasNashPNCC
theme: just-the-docs



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
